### ISSUE TITLE
providers.Object not injecting the original object

### ISSUE THREAD

**Issue by davidcim** [ets-labs/python-dependency-injector#231] opened 2019-10-07 19:05 UTC
In the documentation you can read about the Object provider:

    Object - provider that returns provided instance "as is".

However when I try to inject a parameter from an Object provider I get a different instance. I have been only able to get the original object using a Callable provider.

This code exemplifies the issue:

    from dependency_injector import containers, providers
    
    
    class Obj:
        pass
    
    
    my_obj = Obj()
    
    
    class IocContainer(containers.DeclarativeContainer):
    
        obj1 = providers.Object(
            my_obj,
        )
    
        obj2 = providers.Callable(
            lambda: my_obj
        )
    
    
    ioc = IocContainer()
    print('Original object: ', my_obj)
    print('providers.Object', ioc.obj1())
    print('providers.Callable', ioc.obj2())

As you can see in the output, providers.Object is returning a different instance:

    Original object:  <__main__.Obj object at 0x7fcc0d1e16a0>
    providers.Object <__main__.Obj object at 0x7fcc0d1e17f0>
    providers.Callable <__main__.Obj object at 0x7fcc0d1e16a0>

I am using _Python 3.5.2_ and _dependency-injector 3.14.10_

**Comment by rmk135** [comment] 2019-10-08 18:05
Hello @davidcim ,

You're right, that is not expected behavior. Let me debug this...

Thanks,
Roman

**Comment by rmk135** [comment] 2019-10-08 18:11
Oh gosh, it creates a copy of `Object` provider content. That's weird and should be fixed.

Working on fix...

**Comment by rmk135** [comment] 2019-10-08 18:23
Gosh, this bug is there since [3.0.0](https://github.com/ets-labs/python-dependency-injector/releases/tag/3.0.0) that was published Nov 11, 2016...

**Comment by rmk135** [comment] 2019-10-08 18:55
Fix is published in `3.14.11`.

@davidcim , thanks a lot for reporting the issue.

Roman

**Closed by rmk135** 2019-10-08 18:55 UTC
Labels: bug

**Comment by davidcim** [comment] 2019-10-09 09:51
@rmk135, thank you for fixing it so quickly.

**Comment by rmk135** [comment] 2019-10-09 16:01
@davidcim , please update to `3.14.12`, see #235  for details.
