### ISSUE TITLE
impossible to perform wire when modules are dinamically invoked with importlib.import_module

### ISSUE THREAD

**Issue by Balthus1989** [ets-labs/python-dependency-injector#365] opened 2021-01-19 15:13 UTC
Hello there,
I noticed that an explicit import of a package works smoothly, while a dinamic import causes the wire function to not work properly

When it works:

`from dependency_injector import containers, providers
from dependency_injector.wiring import inject, Provide
from pathlib import Path 

from src.service.costestimator.costestimator import costestimator as CE

if __name__ == '__main__':
    service = 'costestimator'
    customer = 'john_doe'
    plant = '0'

    # Retrieving paths
    root_dir = Path.cwd().parent
    ini_file = service + '_' + customer + '_' + plant + '.ini'
    ini_path = root_dir.joinpath(root_dir, 'config', 'params', ini_file)
    
    # Loading needed libraries
    container = importlib.import_module('src.service.' + service + '.configuration.configuration')
    configuration = container.Container()
    configuration.config.from_ini(ini_path)
    configuration.wire(modules=[sys.modules[__name__]])

    CE_1 = CE()`

In this case, the output is constituted by prints of fields coming from an .ini file (i.e.: the desired output).

In the following case, it does not work:
`
from dependency_injector import containers, providers
from dependency_injector.wiring import inject, Provide
from pathlib import Path 
import importlib

if __name__ == '__main__':
    service = 'costestimator'
    customer = 'john_doe'
    plant = '0'
    
    # Retrieving paths
    root_dir = Path.cwd().parent
    ini_file = service + '_' + customer + '_' + plant + '.ini'
    ini_path = root_dir.joinpath(root_dir, 'config', 'params', ini_file)
    
    # Loading needed libraries
    container = importlib.import_module('src.service.' + service + '.configuration.configuration')
    configuration = container.Container()
    configuration.config.from_ini(ini_path)
    configuration.wire(modules=[sys.modules[__name__]])

    getattr(importlib.import_module('src.service.' + service + '.' + service), service)()
`

in this case, the result is a print of the Provide objects.

The init function of the class costestimator is written as:
`class costestimator():
    def __init__(self, customer_name = Provide[Container.config.customer.customer_name.as_(str)],
                 customer_plant = Provide[Container.config.customer.customer_plant.as_(str)]):`

**Comment by rmk135** [comment] 2021-01-19 18:05
Hi @Balthus1989 , thanks for reporting the issue. I'll check if I could improve it.

**Comment by Balthus1989** [comment] 2021-01-19 21:59
> 
> 
> Hi @Balthus1989 , thanks for reporting the issue. I'll check if I could improve it.

You're welcome. I hope I've been clear in describing the error :-)

**Comment by rmk135** [comment] 2021-01-29 01:00
Hey @Balthus1989 ,

I've analyzed the problem. It is not a bug in existing functionality, but an uncovered use case. I would call it "wiring dynamically imported modules".

I have released version ``4.12.0`` that covers this use case. Here is a sample:

```python
import importlib

from dependency_injector.wiring import register_loader_containers

from .containers import Container


if __name__ == '__main__':
    container = Container()
    register_loader_containers(container)  # <--- installs import hook

    module = importlib.import_module('package.module')
    module.foo()
```

**Comment by rmk135** [comment] 2021-01-29 01:03
Closing the issue. Thanks for providing the use case. Feel free to comment if any issues or questions.

**Comment by Balthus1989** [comment] 2021-02-02 17:28
> 
> 
> Hey @Balthus1989 ,
> 
> I've analyzed the problem. It is not a bug in existing functionality, but an uncovered use case. I would call it "wiring dynamically imported modules".
> 
> I have released version `4.12.0` that covers this use case. Here is a sample:
> 
> ```python
> import importlib
> 
> from dependency_injector.wiring import register_loader_containers
> 
> from .containers import Container
> 
> 
> if __name__ == '__main__':
>     container = Container()
>     register_loader_containers(container)  # <--- installs import hook
> 
>     module = importlib.import_module('package.module')
>     module.foo()
> ```

The problem is that: even the Container class should be imported dinamically, depending on the customer.
Could you provide a code where even the containers are dinamically imported?

Thank you very much

**Comment by Balthus1989** [comment] 2021-02-02 17:32
> 
> 
> Hey @Balthus1989 ,
> 
> I've analyzed the problem. It is not a bug in existing functionality, but an uncovered use case. I would call it "wiring dynamically imported modules".
> 
> I have released version `4.12.0` that covers this use case. Here is a sample:
> 
> ```python
> import importlib
> 
> from dependency_injector.wiring import register_loader_containers
> 
> from .containers import Container
> 
> 
> if __name__ == '__main__':
>     container = Container()
>     register_loader_containers(container)  # <--- installs import hook
> 
>     module = importlib.import_module('package.module')
>     module.foo()
> ```

Another punctuation: using the following code in evoking my class...

`class costestimator(): def __init__(self, customer_name = Provide[Container.config.customer.customer_name.as_(str)], customer_plant = Provide[Container.config.customer.customer_plant.as_(str)]):`

... it states that those fields are not contained in the Container object

**Comment by rmk135** [comment] 2021-02-02 17:37
Well, it should and I have tests for resolving `.as_(str)` correctly so let's debug. Could you, please, print what you have in config?

```python
if __name__ == '__main__':
    ...
    print(container.config())  # <-- Add this
    module = importlib.import_module('package.module')
    module.foo()
```

**Comment by Balthus1989** [comment] 2021-02-05 10:40
> 
> 
> Well, it should and I have tests for resolving `.as_(str)` correctly so let's debug. Could you, please, print what you have in config?
> 
> ```python
> if __name__ == '__main__':
>     ...
>     print(container.config())  # <-- Add this
>     module = importlib.import_module('package.module')
>     module.foo()
> ```

Hi, sorry for the delay of this answer.

I printed the content of the container and I obtained the desiderd result, having on the console all the fields reported in the .ini file

**Comment by rmk135** [comment] 2021-02-05 13:00
> However, if I print Container.config( ) in the class in which I desire to have my .ini fields, I get { }

Got it. That's expected. Instance of the container and container class are two different objects. When you create container objects, all the providers are copied from container class to the container object. Container class is a reference object. It should never change. When you use wiring, you should use container class: ``customer_plant = Provide[Container.config.customer.customer_plant.as_(str)]``. This a reference of what should be injected. Framework will automatically match actual data from container object with a right reference.

From your initial example it seems like you would like to use both wiring and import hooks:

```python
from dependency_injector.wiring import register_loader_containers


container = importlib.import_module('src.service.' + service + '.configuration.configuration')
configuration = container.Container()
configuration.config.from_ini(ini_path)
configuration.wire(modules=[sys.modules[__name__]])
register_loader_containers(container)  # <--- installs import hook
```

If that doesn't work either, please provide a code sample. I'll help to make it work.

**Comment by Balthus1989** [comment] 2021-02-05 13:32
> 
> 
> > However, if I print Container.config( ) in the class in which I desire to have my .ini fields, I get { }
> 
> Got it. That's expected. Instance of the container and container class are two different objects. When you create container objects, all the providers are copied from container class to the container object. Container class is a reference object. It should never change. When you use wiring, you should use container class: `customer_plant = Provide[Container.config.customer.customer_plant.as_(str)]`. This a reference of what should be injected. Framework will automatically match actual data from container object with a right reference.
> 
> From your initial example it seems like you would like to use both wiring and import hooks:
> 
> ```python
> from dependency_injector.wiring import register_loader_containers
> 
> 
> container = importlib.import_module('src.service.' + service + '.configuration.configuration')
> configuration = container.Container()
> configuration.config.from_ini(ini_path)
> configuration.wire(modules=[sys.modules[__name__]])
> register_loader_containers(container)  # <--- installs import hook
> ```
> 
> If that doesn't work either, please provide a code sample. I'll help to make it work.

Now it works! Thank you very much :-)

**Closed** 2021-02-05 13:32 UTC
Labels: feature, question

**Comment by rmk135** [comment] 2021-02-05 14:30
Ok, good!
