### ISSUE TITLE
Make Closing marker working with providers that contains a resource as argument

### ISSUE THREAD

**Issue by kiriharu** [ets-labs/python-dependency-injector#633] opened 2022-11-02 16:21 UTC
Hi! 
 
Is it possible to make the Closing marker work with all types providers that contain a resource inside? For example, in the following code, the Closing marker does not work:

```python
# handlers
@inject
async def create_project(
    request: web.Request,
    project_repository: ProjectRepository = Closing[Provide[Container.project_repository]],
) -> web.Response:
    ....
# di
class Container(containers.DeclarativeContainer):
    db_session = providers.Resource(get_session, database=db)
    project_repository = providers.Factory(
        ProjectRepository,
        session=db_session
    )
```

At this moment it will work if we add a separate resource argument to handler:

```python
@inject
async def create_project(
    request: web.Request,
    project_repository: Session = Closing[Provide[Container.db_session]],
    project_repository: ProjectRepository = Closing[Provide[Container.project_repository]],
) -> web.Response:
    ....
```

**Comment by kiriharu** [comment] 2022-11-02 16:23
I think following issues have same problems: https://github.com/ets-labs/python-dependency-injector/issues/475, https://github.com/ets-labs/python-dependency-injector/issues/455

**Comment by StummeJ** [comment] 2022-11-15 16:36
I'd like to see this as well. More in general it looks like resources used as a dependency to another provider are not encapsulated with the Closing. I've found that if you include the initial resource in your method you're decorating with @inject then it does work, but that seems like an unreasonable public interface

**Comment by StummeJ** [comment] 2022-11-15 20:10
@kiriharu until it's merged, it can be monkey patched with the following code

```py
from typing import Any, Callable
from dependency_injector import providers, wiring
from dependency_injector.wiring import ProvidersMap, _patched_registry, Provide, Provider

# This backports/monkeypatches the dependency injector to allow `Closing` on dependent resources.
# It is extremely important that it is imported BEFORE dependency_injector is used. This can be
# removed once https://github.com/ets-labs/python-dependency-injector/pull/636 is merged and released.

def _locate_dependent_closing_args(provider: providers.Provider) -> dict[str, providers.Provider]:
    if not hasattr(provider, "args"):
        return {}

    closing_deps = {}
    for arg in provider.args:
        if not isinstance(arg, providers.Provider) or not hasattr(arg, "args"):
            continue

        if not arg.args and isinstance(arg, providers.Resource):
            return {str(id(arg)): arg}
        else:
            closing_deps += _locate_dependent_closing_args(arg)
    return closing_deps


def _bind_injections(fn: Callable[..., Any], providers_map: ProvidersMap) -> None:
    patched_callable = _patched_registry.get_callable(fn)
    if patched_callable is None:
        return

    for injection, marker in patched_callable.reference_injections.items():
        provider = providers_map.resolve_provider(marker.provider, marker.modifier)

        if provider is None:
            continue

        if isinstance(marker, Provide):
            patched_callable.add_injection(injection, provider)
        elif isinstance(marker, Provider):
            if isinstance(provider, providers.Delegate):
                patched_callable.add_injection(injection, provider)
            else:
                patched_callable.add_injection(injection, provider.provider)

        if injection in patched_callable.reference_closing:
            patched_callable.add_closing(injection, provider)
            deps = _locate_dependent_closing_args(provider)
            for key, dep in deps.items():
                patched_callable.add_closing(key, dep)

wiring._bind_injections = _bind_injections
```

**Comment by rmk135** [comment] 2022-12-19 02:53
Amazing feature! Thanks to everybody involved and special thanks to @StummeJ for the PR!

**Comment by rmk135** [comment] 2022-12-19 03:15
Published on PyPI in ``4.41.0``.

**Closed by rmk135** 2022-12-19 03:15 UTC
Labels: feature

**Comment by federinik** [comment] 2022-12-21 18:18
Hi @StummeJ @rmk135,

I would really like to use this new feature in my project, but I inject everything as kwargs and they seemd to be ignored, so I made a small change to the new feature to cover this case too, would you mind reviewing it? (Sorry for the double PR, I used a wrong GitHub account and had to remake everything from the beginning).

There's just a little problem: I wasn't able to run tests on my changes (despite I wrote them) and I didn't find any documentation on how to run them, could you lend me a hand on this?

Thank you

**Comment by Stoom** [comment] 2023-01-09 15:30
@federinik I think I just used the pytest command. In any regards, I use VSCode with the python test runner in there too.

**Comment by federinik** [comment] 2023-01-10 10:48
Hi @Stoom,

I can confirm I was able to run tests via `tox` (while I was having some issues with raw `pytest`), thank yoou for your hint!

**Comment by federinik** [comment] 2023-01-18 11:34
Hi @rmk135,

any news? I really, REALLY need this in my project! 😄

Thx

**Comment by rmk135** [comment] 2023-01-18 13:08
Hey @federinik,

Does the PR that you provided above contain complete implementation of what you need?

**Comment by federinik** [comment] 2023-01-18 13:53
Hi @rmk135,

yes, I should be fine with the PR content, as you can see it was just a small detail, while the core of the feature was kinda complete.

Thank you

**Comment by federinik** [comment] 2023-01-23 18:05
Hi @rmk135,
it's been a month since I opened the PR, it's not even this big or complicated (tbh, the current version is broken, being that `+=` is not a valid operator between dictionaries, so it even fixes a bug). **Is there any actual, real problem with my changes?** Is there something that you don't like or that bothers you in any way?

If yes, please tell me what to update the PR.

If no, please either merge it or tell me you won't and what's the reason.

Thank you
