### ISSUE TITLE
Troubles with dependency injector when running pytest with click

### ISSUE THREAD

**Issue by mickaelperrin** [ets-labs/python-dependency-injector#348] opened 2021-01-08 18:31 UTC
Hi,

When I try to run pytest of my CLI app that uses click, I have issue with the dependency injection.

```
_ test_conf ________________________________________________________________

    def test_conf():
        response = runner.invoke(cli, ['key'])
>       assert(response == 'value')
E       assert <Result AttributeError("'Provide' object has no attribute 'from_yaml'")> == 'value'

app/__maint__test.py:10: AssertionError

```

Would you mind having a look at this repo which contains the minimal code to reproduce the issue:
 https://github.com/mickaelperrin/pytest-dependency-injector

Thanks,

**Comment by rmk135** [comment] 2021-01-08 18:45
Hi @mickaelperrin , got it. I'll take a look.

**Comment by rmk135** [comment] 2021-01-11 14:07
To make tests work you need to edit your ``__main__test.py`` to look like this:

```python
from click.testing import CliRunner
from pytest import fixture

import app
from app.__main__ import cli
from app.Container import Container


@fixture
def runner():
    return CliRunner()


@fixture(scope='module', autouse=True)
def container():
    container = Container()
    container.init_resources()
    container.wire(packages=[app])
    return container


def test_conf(runner):
    response = runner.invoke(cli, ['key'])
    assert(response.output == 'value\n')
```

The missing part was a ``container`` fixture. The error you've seen was caused by missing container initialization and  `container.wire()` in tests.

----

I can also suggest you a refactoring for ``Config``. You can use different wiring marker ``Provider`` to inject provider itself, not the result of its call. You will not need to wrap config into singleton in the container. It will help with further injections. If you will need to make a container injection of config provider you use `.provider` attribute:

```python

class Container(containers.DeclarativeContainer):
    config = Config()
    
    other_provider = providers.Factory(..., config=config.provider)
```

<img width="877" alt="Screenshot 2021-01-11 at 08 59 52" src="https://user-images.githubusercontent.com/1742049/104192030-4af6af00-53ec-11eb-966c-7de3f624884c.png">
<img width="867" alt="Screenshot 2021-01-11 at 09 01 47" src="https://user-images.githubusercontent.com/1742049/104192028-4a5e1880-53ec-11eb-9ad8-9d6983c48402.png">

**Comment by rmk135** [comment] 2021-01-11 14:08
I'm closing the issue. Re-open, if needed.

**Closed by rmk135** 2021-01-11 14:08 UTC
Labels: bug, question

**Comment by trungtin** [comment] 2023-08-31 18:49
For wiring the container in `conftest.py`, one could use the following:

```
@pytest.fixture(scope="module", autouse=True)
def container(request: pytest.FixtureRequest):
    container = Container()
    container.init_resources()
    container.wire(modules=[request.module.__name__])
    return container
```
