### ISSUE TITLE
Unable to wire injections, Flask out of context error

### ISSUE THREAD

**Issue by bvanfleet** [ets-labs/python-dependency-injector#408] opened 2021-02-26 07:23 UTC
I'm hoping this is just because I'm new at this.

I'm developing an application, and currently working on converting to use dependency-injector. I've written a container and have been able to get configuration and a data store factory working. However, I'm running into an issue when wiring up injections with a Flask blueprint.

When I follow the documentation and call the function to wire the container, I get a RuntimeError (actually from Flask):

```
Traceback (most recent call last):
  File "c:\source\personal\pydas\src\pydas\__init__.py", line 61, in create_app
    app.container.wire(
  File "src/dependency_injector/containers.pyx", line 250, in dependency_injector.containers.DynamicContainer.wire
  File "C:\Source\Personal\pyDAS\.env\lib\site-packages\dependency_injector\wiring.py", line 238, in wire
    if inspect.isfunction(member):
  File "C:\Python38\lib\inspect.py", line 169, in isfunction
    return isinstance(object, types.FunctionType)
  File "C:\Source\Personal\pyDAS\.env\lib\site-packages\werkzeug-2.0.0rc1-py3.8.egg\werkzeug\local.py", line 379, in __get__
    obj = instance._get_current_object()
  File "C:\Source\Personal\pyDAS\.env\lib\site-packages\werkzeug-2.0.0rc1-py3.8.egg\werkzeug\local.py", line 499, in _get_current_object
    return self.__local()  # type: ignore
  File "C:\Source\Personal\pyDAS\.env\lib\site-packages\flask-1.1.2-py3.8.egg\flask\globals.py", line 38, in _lookup_req_object
    raise RuntimeError(_request_ctx_err_msg)
RuntimeError: Working outside of request context.

This typically means that you attempted to use functionality that needed
an active HTTP request.  Consult the documentation on testing for
information about how to avoid this problem.
```

Although it's from Flask, it is only raised when calling the wire function, passing in the modules to my blueprints. I've refactored my code to no longer use `current_app`, thinking that might have made an impact. My primary app factory can be found here: https://github.com/bvanfleet/pydas/blob/u/bvanfleet/di.support/src/pydas/__init__.py

Has this ever been encountered before? I tried searching through the other issues, but couldn't find an obvious answer.

**Comment by rmk135** [comment] 2021-02-26 13:07
Hi @bvanfleet ,

Try execute wiring in application context (like you do for signals on lines 82-83):

```python
with app.app_context():
    try:
        app.container.wire(
            modules=[acquire,
                     archives,
                     signals,
                     company,
                     configuration,
                     feature,
                     handler,
                     option,
                     statistics])
    except Exception as exc:
        app.logger.error("Unable to wire dependency injection!", exc_info=exc)
        exit(1)
```

**Comment by bvanfleet** [comment] 2021-02-26 15:19
@rmk135

I went ahead and wrapped it with a call to app_context (like you suggested). Unfortunately, the same error as originally posted.

I did take some time to perform additional debugging. It's failing in the `for module in modules` loop in `wiring.wire()` when trying to patch my `routes.acquire` module. I cheated a little by adding a `logging.info` in that loop. It looks like it's finding and attempting to patch the Flask.request object that was imported in the acquire module, which Flask apparently doesn't seem to appreciate.

**Comment by bvanfleet** [comment] 2021-02-26 15:23
For reference, here's the logs from my application attempting to start up, with my typo'd log entries showing the wire patching:

```
2021-02-26 08:16:08,431:INFO:pydas:Starting pyDAS API app
2021-02-26 08:16:08,456:INFO:root:pathing member Any...
2021-02-26 08:16:08,457:INFO:root:pathing member ApplicationContainer...
2021-02-26 08:16:08,457:INFO:root:pathing member BaseContext...
2021-02-26 08:16:08,457:INFO:root:pathing member BaseFormatter...
2021-02-26 08:16:08,458:INFO:root:pathing member Blueprint...
2021-02-26 08:16:08,459:INFO:root:pathing member Company...
2021-02-26 08:16:08,460:INFO:root:pathing member Configuration...
2021-02-26 08:16:08,460:INFO:root:pathing member FeatureToggle...
2021-02-26 08:16:08,461:INFO:root:pathing member FeatureToggles...
2021-02-26 08:16:08,461:INFO:root:pathing member FormatterFactory...
2021-02-26 08:16:08,462:INFO:root:pathing member IexClient...
2021-02-26 08:16:08,462:INFO:root:pathing member NoResultFound...
2021-02-26 08:16:08,463:INFO:root:pathing member Option...
2021-02-26 08:16:08,463:INFO:root:pathing member Provide...
2021-02-26 08:16:08,463:INFO:root:pathing member SignalFactory...
2021-02-26 08:16:08,464:INFO:root:pathing member __builtins__...
2021-02-26 08:16:08,464:INFO:root:pathing member __cached__...
2021-02-26 08:16:08,464:INFO:root:pathing member __doc__...
2021-02-26 08:16:08,464:INFO:root:pathing member __file__...
2021-02-26 08:16:08,465:INFO:root:pathing member __get_output_configuration...
2021-02-26 08:16:08,465:INFO:root:pathing member __loader__...
2021-02-26 08:16:08,465:INFO:root:pathing member __name__...
2021-02-26 08:16:08,465:INFO:root:pathing member __package__...
2021-02-26 08:16:08,466:INFO:root:pathing member __spec__...
2021-02-26 08:16:08,466:INFO:root:pathing member acquire...
2021-02-26 08:16:08,466:INFO:root:pathing member acquire_bp...
2021-02-26 08:16:08,466:INFO:root:pathing member constants...
2021-02-26 08:16:08,466:INFO:root:pathing member datetime...
2021-02-26 08:16:08,467:INFO:root:pathing member inject...
2021-02-26 08:16:08,467:INFO:root:pathing member json...
2021-02-26 08:16:08,467:INFO:root:pathing member jsonify...
2021-02-26 08:16:08,468:INFO:root:pathing member logging...
2021-02-26 08:16:08,468:INFO:root:pathing member make_response...
2021-02-26 08:16:08,468:INFO:root:pathing member reduce...
2021-02-26 08:16:08,468:INFO:root:pathing member request...
2021-02-26 08:16:08,469:ERROR:pydas:Unable to wire dependency injection!
Traceback (most recent call last):
  File "c:\source\personal\pydas\src\pydas\__init__.py", line 68, in create_app
    app.container.wire(
  File "src/dependency_injector/containers.pyx", line 250, in dependency_injector.containers.DynamicContainer.wire
  File "C:\Source\Personal\pyDAS\.env\lib\site-packages\dependency_injector\wiring.py", line 241, in wire
    if inspect.isfunction(member):
  File "C:\Python38\lib\inspect.py", line 169, in isfunction
    return isinstance(object, types.FunctionType)
  File "C:\Source\Personal\pyDAS\.env\lib\site-packages\werkzeug-2.0.0rc1-py3.8.egg\werkzeug\local.py", line 379, in __get__
    obj = instance._get_current_object()
  File "C:\Source\Personal\pyDAS\.env\lib\site-packages\werkzeug-2.0.0rc1-py3.8.egg\werkzeug\local.py", line 499, in _get_current_object
    return self.__local()  # type: ignore
  File "C:\Source\Personal\pyDAS\.env\lib\site-packages\flask-1.1.2-py3.8.egg\flask\globals.py", line 38, in _lookup_req_object
    raise RuntimeError(_request_ctx_err_msg)
RuntimeError: Working outside of request context.

This typically means that you attempted to use functionality that needed
an active HTTP request.  Consult the documentation on testing for
information about how to avoid this problem.
```

**Comment by rmk135** [comment] 2021-02-26 15:36
Got it. That's useful, thanks.

I've seen this error when I did flask examples for dependency injector. I can not recall how a stepped aside of it.

As a workaround, try make wiring before you create `Flask` object. Here is a flask blueprints example from the docs: https://github.com/ets-labs/python-dependency-injector/blob/master/examples/miniapps/flask-blueprints/githubnavigator/application.py#L14

Even if that workaround works, I plan to look for a way to fix it. There are a couple of cases when introspection cases errors with some 3rd party frameworks or even builtin modules. I think I could add an exception to not inspect `flask.request`. I'll get back by the end of the day.

**Comment by bvanfleet** [comment] 2021-02-26 15:58
I tried making the wiring before creating the Flask app, and I still got the same error :shrug:

I'll see if there's any information I can dig up myself later today. As a dirty hack, I moved the import of the `Flask.request` object into the functions that use it (effectively hiding it from the dependency injector). That was able to bypass the problem and get the server running again.

Thanks again for your help. If I am able to find anything else out as I continue working on this, I'll keep you updated.

**Comment by rmk135** [comment] 2021-02-26 16:01
Thank you. My apologies for having it not working properly. I will get it fixed.

**Comment by rmk135** [comment] 2021-02-26 22:12
I was unable to reproduce an issue on my environment. I will try again on weekend.

**Comment by bvanfleet** [comment] 2021-02-27 00:33
Yeah, this is weird. I spun up a new project to see if I could try to repro this one and I couldn't. I tried to mirror much of the structure of the project originally referenced above. Still no dice. I may try to reproduce this over the weekend. If not, I have my workarounds and am okay with that for now.

As a side note, it seems like this is because the Flask.request doesn't support any calls to its `__...__` functions without a context spun up. The underlying werkzeug.LocalProxy is what's getting upset because inspect.isfunction is hitting request.__get__ (there was an old issue reported because doctest had this same problem). However, without being able to repro I'm at a loss here.

**Comment by rmk135** [comment] 2021-02-27 00:40
Yep, right. I'm trying to reproduce it now copying parts of your project and still no luck.

> As a side note, it seems like this is because the Flask.request doesn't support any calls to its __...__ functions without a context spun up.

This is a dark side of introspection. Sometimes I have to handle certain exceptions, e.g. #362 #398 . I believe that one is sort of similar thing. I would like to fix it so it doesn't bother people if they accidentally get in trouble. But I need to find it first :) Thanks a lot for reporting it and doing all this debugging together.

**Comment by rmk135** [comment] 2021-02-27 01:34
How do you start the server?

**Comment by rmk135** [comment] 2021-02-27 01:37
I've installed the app locally and get it up and running. Guess what? All works :)

```
(venv) rmk src [u/bvanfleet/di.support] 🚀 flask run
 * Serving Flask app "pydas" (lazy loading)
 * Environment: development
 * Debug mode: on
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 288-454-072
INFO     [pydas] Starting pyDAS API app
INFO     [pydas] Wiring successful
INFO     [pydas] Starting pyDAS API app
INFO     [pydas] Wiring successful
```

One interesting thing is that log messages appear twice. I have a feeling that there a couple of threads.

**Comment by rmk135** [comment] 2021-02-27 01:59
Alright, I'm totally stuck now :) Will give it a few more tries later. If you wouldn't mind, could you please post how do you run the app and what versions of Flask and Dependency Injector you have.

**Comment by rmk135** [comment] 2021-02-27 13:17
I got it!

<img width="1218" alt="Screenshot 2021-02-27 at 08 12 11" src="https://user-images.githubusercontent.com/1742049/109388202-b5e44280-78d3-11eb-8693-77c5d2737822.png">
<img width="941" alt="Screenshot 2021-02-27 at 08 11 39" src="https://user-images.githubusercontent.com/1742049/109388204-b67cd900-78d3-11eb-9c40-241f6ca6d42a.png">

I looked at your traceback and noticed that `werkzeug` version is an RC. I checked mine. It was `1.0.1`. That what I had installed with the latest flask. When I updated `werkzeug` to RC and tried to make `isinstance(request, types.FunctionType)` that finally crashed.

Working on a fix.

**Comment by rmk135** [comment] 2021-02-27 15:32
@bvanfleet 
Fixed in version ``4.27.0``. Thanks for reporting the issue and help in finding the root cause. It was a puzzling one :)

**Closed by rmk135** 2021-02-27 15:32 UTC
Labels: bug

**Comment by bvanfleet** [comment] 2021-02-28 00:44
That's great to hear, I was just about to report that I had a reproducable project that you could have worked with (sorry I was AFK for too long). Thanks again for catching and fixing this for me!

**Comment by rmk135** [comment] 2021-02-28 15:21
Thanks! If any other problems - feel free to open an issue. `PyDAS` is a great project btw!
